import {
  FaCar,
  FaMotorcycle,
  FaShip,
  FaTruck,
  FaHome,
  FaBuilding,
  FaLandmark,
  FaMobileAlt,
  FaTabletAlt,
  FaBriefcase,
  FaUserTie,
  FaStethoscope,
  FaTv,
  FaLaptop,
  FaGamepad,
  FaBlender,
  FaCouch,
  FaChair,
  FaPalette,
  FaUtensils,
  FaTshirt,
  FaVenusMars,
  FaSprayCan,
  FaRing,
  FaHeart,
  FaDog,
  FaCat,
  FaDove,
  FaBone,
  FaBaby,
  FaTshirt as FaShirt,
  FaBreadSlice,
  FaBed,
  FaGamepad as FaToyIcon,
  FaGuitar,
  FaIndustry,
  FaHardHat,
  FaCogs,
  FaDesktop,
  FaTools,
  FaWrench,
  FaBoxes,
  FaHandshake,
  FaPhone,
  FaHashtag,
} from "react-icons/fa";

import {
  MdElectricCar,
  MdLocalGasStation,
  MdDirectionsCar,
  MdApartment,
  MdVilla,
  MdBeachAccess,
  MdBusiness,
  MdLandscape,
  MdHeadphones,
  MdAccountBalance,
  MdEngineering,
  MdDesignServices,
  MdSupportAgent,
  MdConstruction,
  MdBusinessCenter,
  MdLocalShipping,
  MdSchool,
  MdPeople,
  MdTravelExplore,
  MdComputer,
  MdCampaign,
  MdLocalHospital,
  MdSell,
  MdAdminPanelSettings,
  MdGavel,
  MdWork,
  MdSpeaker,
  MdVideogameAsset,
  MdPhotoCamera,
  MdKitchen,
  MdTableRestaurant,
  MdPalette,
  MdYard,
  MdWbIncandescent,
  MdCheckroom,
  MdWatch,
  MdPets,
  MdChildCare,
  MdToys,
  MdDirectionsBike,
  MdMenuBook,
  MdCasino,
  MdMovie,
  MdFitnessCenter,
  MdCreate,
  MdConfirmationNumber,
  MdLuggage,
  MdFactory,
  MdAgriculture,
  MdMedicalServices,
  MdEventSeat,
  MdRestaurant,
  MdStorefront,
  MdMiscellaneousServices,
  MdCarRepair,
  MdEvent,
  MdSpa,
  MdHomeRepairService,
  MdMoving,
  MdPets as MdPetCare,
  MdCastForEducation,
} from "react-icons/md";

import type { IconType } from "react-icons";

export type CategoryIconType = IconType;
type SubCategoryIcons = Record<string, CategoryIconType>;

type CategoryIconsType = Record<
  string,
  { icon: CategoryIconType; subCategories: SubCategoryIcons }
>;

export const categoryIcons: CategoryIconsType = {
  vehicles: {
    icon: FaCar,
    subCategories: {
      cars_for_sale: MdDirectionsCar,
      cars_for_rent: MdElectricCar,
      tyres_batteries_oils_accessories: MdLocalGasStation,
      car_spare_parts: FaTools,
      motorcycles_accessories: FaMotorcycle,
      boats_watercraft: FaShip,
      heavy_trucks_buses_other_vehicles: FaTruck,
    },
  },
  properties: {
    icon: FaHome,
    subCategories: {
      apartments_for_sale: MdApartment,
      apartments_for_rent: FaBuilding,
      villas_for_sale: MdVilla,
      villas_for_rent: FaLandmark,
      vacation_homes_for_sale: MdBeachAccess,
      vacation_homes_for_rent: MdTravelExplore,
      commercial_for_sale: MdBusiness,
      commercial_for_rent: MdStorefront,
      buildings_lands: MdLandscape,
    },
  },
  mobiles_tablets: {
    icon: FaMobileAlt,
    subCategories: {
      mobile_phones: FaPhone,
      tablets: FaTabletAlt,
      mobile_tablet_accessories: MdHeadphones,
      mobile_numbers: FaHashtag,
    },
  },
  jobs: {
    icon: FaBriefcase,
    subCategories: {
      accounting_finance_banking: MdAccountBalance,
      engineering: MdEngineering,
      designers: MdDesignServices,
      customer_service_call_center: MdSupportAgent,
      workers_technicians: MdConstruction,
      management_consulting: MdBusinessCenter,
      drivers_delivery: MdLocalShipping,
      education: MdSchool,
      hr: MdPeople,
      tourism_travel_hospitality: MdTravelExplore,
      it_telecom: MdComputer,
      marketing_pr: MdCampaign,
      medical_healthcare_nursing: MdLocalHospital,
      sales: MdSell,
      secretarial: FaUserTie,
      guards_security: MdAdminPanelSettings,
      legal_lawyers: MdGavel,
      other_jobs: MdWork,
    },
  },
  electronics_home_appliances: {
    icon: FaTv,
    subCategories: {
      tv_audio_video: MdSpeaker,
      computers_accessories: FaLaptop,
      video_games_consoles: MdVideogameAsset,
      cameras_imaging: MdPhotoCamera,
      home_appliances: FaBlender,
    },
  },
  home_garden: {
    icon: FaCouch,
    subCategories: {
      furniture: MdTableRestaurant,
      office_furniture: FaChair,
      home_decoration_accessories: MdPalette,
      bathroom_kitchen: MdKitchen,
      fabric_bedding_curtains: FaBed,
      garden_outdoor: MdYard,
      kitchenware: FaUtensils,
      lighting: MdWbIncandescent,
    },
  },
  fashion_beauty: {
    icon: FaTshirt,
    subCategories: {
      womens_clothing: MdCheckroom,
      mens_clothing: FaVenusMars,
      womens_cosmetics: FaSprayCan,
      womens_accessories_personal_care: FaRing,
      mens_accessories_personal_care: MdWatch,
    },
  },
  pets_animals: {
    icon: MdPets,
    subCategories: {
      dogs: FaDog,
      cats: FaCat,
      birds_pigeons: FaDove,
      other_pets_animals: FaHeart,
      pet_accessories_care_products: FaBone,
    },
  },
  kids_babies: {
    icon: FaBaby,
    subCategories: {
      baby_mom_healthcare: MdChildCare,
      baby_clothing: FaShirt,
      baby_feeding_tools: FaBreadSlice,
      cribs_strollers_carriers: MdEventSeat,
      toys: MdToys,
      other_baby_items: FaToyIcon,
    },
  },
  hobbies_books_sports: {
    icon: FaGamepad,
    subCategories: {
      antiques_collectibles: FaPalette,
      bicycles: MdDirectionsBike,
      books: MdMenuBook,
      board_card_games: MdCasino,
      movies_music: MdMovie,
      musical_instruments: FaGuitar,
      sports_equipment: MdFitnessCenter,
      study_tools: MdCreate,
      tickets_vouchers: MdConfirmationNumber,
      luggage: MdLuggage,
      other_items: FaBoxes,
    },
  },
  business_industrial: {
    icon: MdFactory,
    subCategories: {
      agriculture: MdAgriculture,
      construction: FaHardHat,
      industrial_equipment: FaCogs,
      medical_equipment: MdMedicalServices,
      office_furniture_equipment: FaDesktop,
      restaurants_equipment: MdRestaurant,
      whole_business_for_sale: FaHandshake,
      other_business_industrial_agriculture: FaIndustry,
    },
  },
  services: {
    icon: MdMiscellaneousServices,
    subCategories: {
      business_services: MdBusinessCenter,
      car_services: MdCarRepair,
      event_services: MdEvent,
      health_beauty_services: MdSpa,
      home_maintenance: MdHomeRepairService,
      medical_services: FaStethoscope,
      movers: MdMoving,
      pet_services: MdPetCare,
      education_services: MdCastForEducation,
      other_services: FaWrench,
    },
  },
};
