import {
  FaCar,
  FaMotorcycle,
  FaShip,
  FaTruck,
  FaHome,
  FaBuilding,
  FaLandmark,
  FaMobileAlt,
  FaTabletAlt,
  FaBriefcase,
  FaUserTie,
  FaStethoscope,
  FaTv,
  FaLaptop,
  FaGamepad,
  FaBlender,
  FaCouch,
  FaChair,
  FaPalette,
  FaUtensils,
  FaTshirt,
  FaVenusMars,
  FaSprayCan,
  FaRing,
  FaHeart,
  FaDog,
  FaCat,
  FaDove,
  FaBone,
  FaBaby,
  FaTshirt as FaShirt,
  FaBreadSlice,
  FaBed,
  FaGamepad as FaToyIcon,
  FaGuitar,
  FaIndustry,
  FaHardHat,
  FaCogs,
  FaDesktop,
  FaTools,
  FaWrench,
  FaBoxes,
  FaHandshake,
  FaPhone,
  FaHashtag,
} from "react-icons/fa";

import {
  MdElectricCar,
  MdLocalGasStation,
  MdDirectionsCar,
  MdApartment,
  MdVilla,
  MdBeachAccess,
  MdBusiness,
  MdLandscape,
  MdHeadphones,
  MdAccountBalance,
  MdEngineering,
  MdDesignServices,
  MdSupportAgent,
  MdConstruction,
  MdBusinessCenter,
  MdLocalShipping,
  MdSchool,
  MdPeople,
  MdTravelExplore,
  MdComputer,
  MdCampaign,
  MdLocalHospital,
  MdSell,
  MdAdminPanelSettings,
  MdGavel,
  MdWork,
  MdSpeaker,
  MdVideogameAsset,
  MdPhotoCamera,
  MdKitchen,
  MdTableRestaurant,
  MdPalette,
  MdYard,
  MdWbIncandescent,
  MdCheckroom,
  MdWatch,
  MdPets,
  MdChildCare,
  MdToys,
  MdDirectionsBike,
  MdMenuBook,
  MdCasino,
  MdMovie,
  MdFitnessCenter,
  MdCreate,
  MdConfirmationNumber,
  MdLuggage,
  MdFactory,
  MdAgriculture,
  MdMedicalServices,
  MdEventSeat,
  MdRestaurant,
  MdStorefront,
  MdMiscellaneousServices,
  MdCarRepair,
  MdEvent,
  MdSpa,
  MdHomeRepairService,
  MdMoving,
  MdPets as MdPetCare,
  MdCastForEducation,
} from "react-icons/md";

import type { IconType } from "react-icons";

export type CategoryIconType = IconType;

type CategoryIconsType = Record<
  string,
  { icon: CategoryIconType; categories?: CategoryIconsType }
>;

export const categoryIcons: CategoryIconsType = {
  vehicles: {
    icon: FaCar,
    categories: {
      "cars-for-sale": { icon: MdDirectionsCar },
      "cars-for-rent": { icon: MdElectricCar },
      "tyres-batteries-oils-accessories": { icon: MdLocalGasStation },
      "car-spare-parts": { icon: FaTools },
      "motorcycles-accessories": { icon: FaMotorcycle },
      "boats-watercraft": { icon: FaShip },
      "heavy-trucks-buses-other-vehicles": { icon: FaTruck },
    },
  },
  properties: {
    icon: FaHome,
    categories: {
      "apartments-for-sale": { icon: MdApartment },
      "apartments-for-rent": { icon: FaBuilding },
      "villas-for-sale": { icon: MdVilla },
      "villas-for-rent": { icon: FaLandmark },
      "vacation-homes-for-sale": { icon: MdBeachAccess },
      "vacation-homes-for-rent": { icon: MdTravelExplore },
      "commercial-for-sale": { icon: MdBusiness },
      "commercial-for-rent": { icon: MdStorefront },
      "buildings-lands": { icon: MdLandscape },
    },
  },
  "mobiles-tablets": {
    icon: FaMobileAlt,
    categories: {
      "mobile-phones": { icon: FaPhone },
      tablets: { icon: FaTabletAlt },
      "mobile-tablet-accessories": { icon: MdHeadphones },
      "mobile-numbers": { icon: FaHashtag },
    },
  },
  jobs: {
    icon: FaBriefcase,
    categories: {
      "accounting-finance-banking": { icon: MdAccountBalance },
      engineering: { icon: MdEngineering },
      designers: { icon: MdDesignServices },
      "customer-service-call-center": { icon: MdSupportAgent },
      "workers-technicians": { icon: MdConstruction },
      "management-consulting": { icon: MdBusinessCenter },
      "drivers-delivery": { icon: MdLocalShipping },
      education: { icon: MdSchool },
      hr: { icon: MdPeople },
      "tourism-travel-hospitality": { icon: MdTravelExplore },
      "it-telecom": { icon: MdComputer },
      "marketing-pr": { icon: MdCampaign },
      "medical-healthcare-nursing": { icon: MdLocalHospital },
      sales: { icon: MdSell },
      secretarial: { icon: FaUserTie },
      "guards-security": { icon: MdAdminPanelSettings },
      "legal-lawyers": { icon: MdGavel },
      "other-jobs": { icon: MdWork },
    },
  },
  "electronics-home-appliances": {
    icon: FaTv,
    categories: {
      "tv-audio-video": { icon: MdSpeaker },
      "computers-accessories": { icon: FaLaptop },
      "video-games-consoles": { icon: MdVideogameAsset },
      "cameras-imaging": { icon: MdPhotoCamera },
      "home-appliances": { icon: FaBlender },
    },
  },
  "home-office": {
    icon: FaCouch,
    categories: {
      furniture: { icon: MdTableRestaurant },
      "office-furniture": { icon: FaChair },
      "home-decoration-accessories": { icon: MdPalette },
      "bathroom-kitchen": { icon: MdKitchen },
      "fabric-bedding-curtains": { icon: FaBed },
      "garden-outdoor": { icon: MdYard },
      kitchenware: { icon: FaUtensils },
      lighting: { icon: MdWbIncandescent },
    },
  },
  "fashion-beauty": {
    icon: FaTshirt,
    categories: {
      "womens-clothing": { icon: MdCheckroom },
      "mens-clothing": { icon: FaVenusMars },
      "womens-cosmetics": { icon: FaSprayCan },
      "womens-accessories-personal-care": { icon: FaRing },
      "mens-accessories-personal-care": { icon: MdWatch },
    },
  },
  "pets-animals": {
    icon: MdPets,
    categories: {
      dogs: { icon: FaDog },
      cats: { icon: FaCat },
      "birds-pigeons": { icon: FaDove },
      "other-pets-animals": { icon: FaHeart },
      "pet-accessories-care-products": { icon: FaBone },
    },
  },
  "kids-babies": {
    icon: FaBaby,
    categories: {
      "baby-mom-healthcare": { icon: MdChildCare },
      "baby-clothing": { icon: FaShirt },
      "baby-feeding-tools": { icon: FaBreadSlice },
      "cribs-strollers-carriers": { icon: MdEventSeat },
      toys: { icon: MdToys },
      "other-baby-items": { icon: FaToyIcon },
    },
  },
  "hobbies-books-sports": {
    icon: FaGamepad,
    categories: {
      "antiques-collectibles": { icon: FaPalette },
      bicycles: { icon: MdDirectionsBike },
      books: { icon: MdMenuBook },
      "board-card-games": { icon: MdCasino },
      "movies-music": { icon: MdMovie },
      "musical-instruments": { icon: FaGuitar },
      "sports-equipment": { icon: MdFitnessCenter },
      "study-tools": { icon: MdCreate },
      "tickets-vouchers": { icon: MdConfirmationNumber },
      luggage: { icon: MdLuggage },
      "other-items": { icon: FaBoxes },
    },
  },
  "business-industrial": {
    icon: MdFactory,
    categories: {
      agriculture: { icon: MdAgriculture },
      construction: { icon: FaHardHat },
      "industrial-equipment": { icon: FaCogs },
      "medical-equipment": { icon: MdMedicalServices },
      "office-furniture-equipment": { icon: FaDesktop },
      "restaurants-equipment": { icon: MdRestaurant },
      "whole-business-for-sale": { icon: FaHandshake },
      "other-business-industrial-agriculture": { icon: FaIndustry },
    },
  },
  services: {
    icon: MdMiscellaneousServices,
    categories: {
      "business-services": { icon: MdBusinessCenter },
      "car-services": { icon: MdCarRepair },
      "event-services": { icon: MdEvent },
      "health-beauty-services": { icon: MdSpa },
      "home-maintenance": { icon: MdHomeRepairService },
      "medical-services": { icon: FaStethoscope },
      movers: { icon: MdMoving },
      "pet-services": { icon: MdPetCare },
      "education-services": { icon: MdCastForEducation },
      "other-services": { icon: FaWrench },
    },
  },
};
