import {
  Tablet,
  CarFront,
  LucideProps,
  Car,
  Smartphone,
  Disc,
  TabletSmartphone,
  Home,
  Briefcase,
  Tv,
  Cpu,
  Gamepad,
  Camera,
  Wrench,
  Coffee,
  Heart,
  Users,
  BookOpen,
  ShoppingBag,
  Anchor,
  Hash,
  Activity,
  Shield,
  Gavel,
  TreeDeciduous,
  Lamp,
  Bike,
  Music,
  Ticket,
  Backpack,
  Factory,
  Leaf,
  HardHat,
  Calendar,
  Truck,
  Dumbbell,
  Fuel,
  Brush,
} from "lucide-react";
import type { ForwardRefExoticComponent, RefAttributes } from "react";

export type CategoryIconType = ForwardRefExoticComponent<
  Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
>;
type SubCategoryIcons = Record<string, CategoryIconType>;

type CategoryIconsType = Record<
  string,
  { icon: CategoryIconType; subCategories: SubCategoryIcons }
>;

export const categoryIcons: CategoryIconsType = {
  vehicles: {
    icon: CarFront,
    subCategories: {
      cars_for_sale: Car,
      cars_for_rent: Car,
      tyres_batteries_oils_accessories: Wrench,
      car_spare_parts: Wrench,
      motorcycles_accessories: CarFront,
      boats_watercraft: Anchor,
      heavy_trucks_buses_other_vehicles: Truck,
    },
  },
  properties: {
    icon: Home,
    subCategories: {
      apartments_for_sale: Home,
      apartments_for_rent: Home,
      villas_for_sale: Home,
      villas_for_rent: Home,
      vacation_homes_for_sale: Home,
      vacation_homes_for_rent: Home,
      commercial_for_sale: Briefcase,
      commercial_for_rent: Briefcase,
      buildings_lands: Home,
    },
  },
  mobiles_tablets: {
    icon: TabletSmartphone,
    subCategories: {
      mobile_phones: Smartphone,
      tablets: Tablet,
      mobile_tablet_accessories: Disc,
      mobile_numbers: Hash,
    },
  },
  jobs: {
    icon: Briefcase,
    subCategories: {
      accounting_finance_banking: Briefcase,
      engineering: Wrench,
      designers: Brush,
      customer_service_call_center: Users,
      workers_technicians: Wrench,
      management_consulting: Briefcase,
      drivers_delivery: CarFront,
      education: BookOpen,
      hr: Users,
      tourism_travel_hospitality: Activity,
      it_telecom: Cpu,
      marketing_pr: Heart,
      medical_healthcare_nursing: Heart,
      sales: ShoppingBag,
      secretarial: Briefcase,
      guards_security: Shield,
      legal_lawyers: Gavel,
      other_jobs: Briefcase,
    },
  },
  electronics_home_appliances: {
    icon: Tv,
    subCategories: {
      tv_audio_video: Tv,
      computers_accessories: Cpu,
      video_games_consoles: Gamepad,
      cameras_imaging: Camera,
      home_appliances: Wrench,
    },
  },
  home_garden: {
    icon: Home,
    subCategories: {
      furniture: ShoppingBag,
      office_furniture: ShoppingBag,
      home_decoration_accessories: Heart,
      bathroom_kitchen: Wrench,
      fabric_bedding_curtains: Coffee,
      garden_outdoor: TreeDeciduous,
      kitchenware: Wrench,
      lighting: Lamp,
    },
  },
  fashion_beauty: {
    icon: Heart,
    subCategories: {
      womens_clothing: ShoppingBag,
      mens_clothing: ShoppingBag,
      womens_cosmetics: Brush,
      womens_accessories_personal_care: Heart,
      mens_accessories_personal_care: Coffee,
    },
  },
  pets_animals: {
    icon: Heart,
    subCategories: {
      dogs: Heart,
      cats: Heart,
      birds_pigeons: Anchor,
      other_pets_animals: Heart,
      pet_accessories_care_products: Wrench,
    },
  },
  kids_babies: {
    icon: Users,
    subCategories: {
      baby_mom_healthcare: Heart,
      baby_clothing: ShoppingBag,
      baby_feeding_tools: Coffee,
      cribs_strollers_carriers: CarFront,
      toys: ShoppingBag,
      other_baby_items: ShoppingBag,
    },
  },
  hobbies_books_sports: {
    icon: Gamepad,
    subCategories: {
      antiques_collectibles: Heart,
      bicycles: Bike,
      books: BookOpen,
      board_card_games: Gamepad,
      movies_music: Music,
      musical_instruments: Music,
      sports_equipment: Dumbbell,
      study_tools: BookOpen,
      tickets_vouchers: Ticket,
      luggage: Backpack,
      other_items: ShoppingBag,
    },
  },
  business_industrial: {
    icon: Factory,
    subCategories: {
      agriculture: Leaf,
      construction: HardHat,
      industrial_equipment: Wrench,
      medical_equipment: Heart,
      office_furniture_equipment: ShoppingBag,
      restaurants_equipment: Coffee,
      whole_business_for_sale: Briefcase,
      other_business_industrial_agriculture: Wrench,
    },
  },
  services: {
    icon: Wrench,
    subCategories: {
      business_services: Briefcase,
      car_services: CarFront,
      event_services: Calendar,
      health_beauty_services: Heart,
      home_maintenance: Wrench,
      medical_services: Heart,
      movers: Truck,
      pet_services: Heart,
      education_services: BookOpen,
      other_services: Wrench,
    },
  },
};
